### ISSUE TITLE
How can I convert the models between keras and pytorch using onnx ?

### ISSUE THREAD

**Issue by lith0613** [onnx/tutorials#103]
I need to run the experiments on the models written by pytorch and keras respectively. I wish to ensure that the model parameters used by keras and pytorch are the same, so I want to convert the trained pytorch model to keras or convert the trained keras model to pytorch. Thanks for your help !

**Comment by prasanthpul** [comment]
Can you convert Keras to ONNX and PyTorch to ONNX and then compare the results?

**Comment by lith0613** [comment]
> Can you convert Keras to ONNX and PyTorch to ONNX and then compare the results?

Can I convert the onnx model into pytorch ?

**Comment by prasanthpul** [comment]
Any reason you need to convert it back to PyTorch?

**Comment by lith0613** [comment]
> Any reason you need to convert it back to PyTorch?

Just due to my code was writen in pytorch

**Comment by don-tpanic** [comment]
@lith0613 Hi, did you manage to solve the problem? Same goal here:)
