### ISSUE TITLE
ONNXRuntimeError when converting a Keras model

### ISSUE THREAD

**Issue by srikanthderebail** [onnx/tutorials#111]
Hello,

I am trying to convert a keras model with the following configuration

input = Input(shape=(len,1))
hidden_1, state_last = SimpleRNN(units=n_h1, activation='tanh',return_sequences=True, \
kernel_initializer='orthogonal',kernel_regularizer=regularizers.l2(0.01),recurrent_regularizer=regularizers.l2(0.0),\
use_bias=True,return_state=True)(input)
hidden_2 = Dense(units=n_h2,activation='tanh',kernel_regularizer=regularizers.l2(0.001), use_bias=True)(hidden_1)
output = Dense(units=1,activation='linear',kernel_regularizer=regularizers.l2(0.001), use_bias=True)(hidden_2)
model = Model(inputs=input,outputs=output)

I used keras2onnx.convert_keras to generate the onnx file. However, when I use onnxruntime I get the following error,
RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : No suitable kernel definition found for op Split(2) (node dense_1_imp_root__dense_1_unstack)

I am using onnx version 1.3.0, onnxruntime version 0.2.1 keras2onnx version 1.3.0.

**Comment by wenbingl** [comment]
The root cause is Split doesn't support integer type in ONNXRuntime implementation. And I just update the keras2onnx to accommodate this issue. please pull the latest keras2onnx code and have a try.

**Comment by srikanthderebail** [comment]
Thank you for the update. It works like a charm now!
