### ISSUE TITLE
Add export support for torch.var()

### ISSUE THREAD

**Issue by InnerPeaceStudios** [onnx/tutorials#125]
I am new in deep learning and pytorch, an error occurred when I want to export a model:

     RuntimeError: ONNX export failed: Couldn't export operator aten::var

I followed the tutorial to add support for pytorch operator in this repo, but I can't make it right.

The line in the VariableType.h file is:

     Tensor var(const Tensor & self, IntArrayRef dim, bool unbiased, bool keepdim) const override;

**Comment by iver56** [comment]
The solution for me was to use `torch.std(...) ** 2` instead of `torch.var(...)` for ONNX compatibility
