### ISSUE TITLE
Unable to convert Fully connected layer from CNTK to ONNX

### ISSUE THREAD

**Issue by almeida29** [onnx/tutorials#13]
model.load() CNTK API does not generate Fully Connected layer in ONNX.
Instead it produces two layers: MatMul and Add.
Is there a way to generate the Fully Connected operator while converting from CNTK to ONNX format?

**Comment by ebarsoum** [comment]
CNTK doesn't have a fully connected layer as single OP, the Dense layer in CNTK is a high level API that uses MatMul and Add. Furthermore, FC OP in ONNX is under experiments which mean not all frameworks support it.

**Comment by almeida29** [comment]
Thanks for the prompt reply. Does any other Framework support the FC OP in ONNX and is there any documention on how to use the experimental FC OP in ONNX.

**Comment by ebarsoum** [comment]
You should GEMM instead FC have been removed from ONNX.
