### ISSUE TITLE
Int64 -> Int32 Tensors

### ISSUE THREAD

**Issue by dvd42** [onnx/tutorials#130]
I am trying to import [this model](https://github.com/onnx/models/tree/master/ssd) from the onnx model zoo to OpenCV. However OpenCV does not support 64 bit integers and some of the tensors in this model seem to be of Int64 type.
Is there a way to convert the Int64 tensors inside the model to Int32?

**Comment by blacklong617** [comment]
@dvd42 Have you got the way to convert Int64 to Int32 ?

**Comment by dvd42** [comment]
@blacklong617, no sorry I thought I had explained why I closed the issue before doing so. It seems that this was an error coming from the OpenCV ONNX parser. But no, I did not find a way of doing so.

**Comment by blacklong617** [comment]
@dvd42 Thank you for your reply, I found that using other methods can circumvent this problem.

**Comment by mike07026** [comment]
> @dvd42 Thank you for your reply, I found that using other methods can circumvent this problem.

Can you tell me how ? Thanks in advance.

**Comment by Ahmet57** [comment]
This is a problem for me. If anyone who knows the solution, can help
