### ISSUE TITLE
How to convert a python based model without any framework to onnx?

### ISSUE THREAD

**Issue by ac4922** [onnx/tutorials#138]
Hi, 
I am looking to convert a python based custom model which is not based on any frameworks such as sklearn or tensorflow etc. 

Could you please help me with this? Or guide me to suitable resources which can be useful for this use case?

Thanks

**Comment by prasanthpul** [comment]
The frameworks have converters and exports that generate ONNX models.
If you have completely custom code, you will need to generate the ONNX model yourself. The format of the file is described [here](https://github.com/onnx/onnx/blob/master/docs/IR.md) and defined [here](https://github.com/onnx/onnx/blob/master/onnx/onnx.in.proto). You'll also need to map the computations in your code to the [operators defined](https://github.com/onnx/onnx/blob/master/docs/Operators.md) in ONNX .

**Comment by ac4922** [comment]
> The frameworks have converters and exports that generate ONNX models. You can look at their code for some examples.
> If you have completely custom code, you will need to generate the ONNX model yourself. The format of the file is described [here](https://github.com/onnx/onnx/blob/master/docs/IR.md) and defined [here](https://github.com/onnx/onnx/blob/master/onnx/onnx.in.proto). You'll also need to map the computations in your code to the [operators defined](https://github.com/onnx/onnx/blob/master/docs/Operators.md) in ONNX .

Thanks!
