### ISSUE TITLE
Cannot download squeezenet model in Caffe2

### ISSUE THREAD

**Issue by kyoro1** [onnx/tutorials#16]
Before trying to export caffe2 model to ONNX using [this link](https://github.com/onnx/tutorials/blob/master/tutorials/Caffe2OnnxExport.ipynb), we should download the original model. But, I couldn't do it.

```sh
$ python -m caffe2.python.models.download squeezenet
Downloading from https://s3.amazonaws.com/caffe2/models/squeezenet/predict_net.pb
Abort: Could not download model. [HTTP Error] 404: Not Found.
```

Tentatively, I tried to check the URL directly, the following message was shown:

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>models/squeezenet/predict_net.pb</Key>
<RequestId>D8865372FE30D4BA</RequestId>
<HostId>
6llei6m+tX6CqTPlhpjsYVHIcPj4UED5+ZNP3VMiOWQZHEmGjnG/OvxBMeuxpH26/5Bs4O7I91o=
</HostId>
</Error>
```

Do we need any other instructions?

**Comment by dzhulgakov** [comment]
Hm, seems like that script is broken - reported in C2 repo.

You can grab the model from https://github.com/caffe2/caffe2/wiki/Model-Zoo directly for now

**Comment by kyoro1** [comment]
@dzhulgakov Thanks, but can you advise a quick sample with the [reference](https://github.com/caffe2/caffe2/wiki/Model-Zoo)?

**Comment by kyoro1** [comment]
Do you mean that we'll use `wget`, for example?

```py
wget https://github.com/caffe2/models/blob/master/squeezenet/predict_net.pb
```

**Comment by orionr** [comment]
Hi @kyoro1. We're investigating, but for now you can do

```
wget https://s3.amazonaws.com/download.caffe2.ai/models/squeezenet/predict_net.pb
wget https://s3.amazonaws.com/download.caffe2.ai/models/squeezenet/init_net.pb
```

**Comment by houseroad** [comment]
This is fixed already. Thanks @orionr.

**Comment by mezab** [comment]
> Hi @kyoro1. We're investigating, but for now you can do
> 
> ```
> wget https://s3.amazonaws.com/download.caffe2.ai/models/squeezenet/predict_net.pb
> wget https://s3.amazonaws.com/download.caffe2.ai/models/squeezenet/init_net.pb
> ```

Hi!

I just download both files, and I got the response below this, but I don't know which is the current location of those files. Do you have any suggestion about that ?

**

- 2018-12-24 15:07:58--  https://s3.amazonaws.com/download.caffe2.ai/models/sque                                                                             ezenet/predict_net.pb
- Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.111.21
- Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.111.21|:443... connecte                                                                             d.
- HTTP request sent, awaiting response... 200 OK
- Length: 6175 (6.0K) [binary/octet-stream]
- Saving to: ‘predict_net.pb.1’
- 
- predict_net.pb.1    100%[===================>]   6.03K  --.-KB/s    in 0s
- 
- 2018-12-24 15:07:58 (208 MB/s) - ‘predict_net.pb.1’ saved [6175/6175]

**

Thanks,
