### ISSUE TITLE
How to convert a pytorch model to onnx model as the input is variable length?

### ISSUE THREAD

**Issue by wizardk** [onnx/tutorials#163]
I've seen the tutorial [https://github.com/onnx/tutorials/blob/master/tutorials/PytorchOnnxExport.ipynb](url).
It shows how to convert a pytorch model to onnx model as the input is fixed shape. Using the same way with a dummy input in fixed shape when the real input is variable length?

**Comment by wizardk** [comment]
Got it, appointing dynamic_axes.

**Comment by frankiedrake** [comment]
> 

Hello, how do specify the actual data size when using the exported model with a `dynamic_axes` parameter?
I've tried a lot of ways, but always get error 
```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: modelInput for the following indices
 index: 1 Got: 1425936 Expected: 100000
 Please fix either the inputs or the model.
```

I've set the `dynamic_axes` this way:
```
torch.onnx.export(...
         dynamic_axes={'modelInput' : {0 : 'batch_size'},
                                'modelOutput' : {0 : 'batch_size'}}) 
```
