### ISSUE TITLE
problems in input format when using OnnxRuntimeServerSSDModel

### ISSUE THREAD

**Issue by amy-hyunji** [onnx/tutorials#202]
I am having trouble when using OnnxRuntimeServerSSDModel with a new onnx model. 
It seems like ssd.onnx has one input "image" and has three attributes. 
My onnx model have three input with no attributes for each. How can I modify the input format? 

Thanks :)

**Comment by pranavsharma** [comment]
Every input is associated with shape, type and the raw data. You need to populate these for all the inputs. As per the python notebook, if you've 3 inputs, you can populate them as follows. Hope this helps!

```
request_message.inputs["input_1"].data_type = input_tensor.data_type
request_message.inputs["input_1"].dims.extend(input_tensor.dims)
request_message.inputs["input_1"].raw_data = input_tensor.raw_data

request_message.inputs["input_2"].data_type = input_tensor.data_type
request_message.inputs["input_2"].dims.extend(input_tensor.dims)
request_message.inputs["input_2"].raw_data = input_tensor.raw_data

request_message.inputs["input_3"].data_type = input_tensor.data_type
request_message.inputs["input_3"].dims.extend(input_tensor.dims)
request_message.inputs["input_3"].raw_data = input_tensor.raw_data
```
