### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export operator aten::adaptive_max_pool2d

### ISSUE THREAD

**Issue by JayLSU** [onnx/tutorials#204]
I want to convert my pytorch network (.pth) into onnx, however, since I used adaptive_max_pool2d, I got error "RuntimeError: ONNX export failed: Couldn't export operator aten::adaptive_max_pool2d". Following some suggestions, I added "operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK" when I convert the model. Then I got the following warning:
"UserWarning: ONNX export failed on adaptive_max_pool2d because output size that are not factor of input size not supported"
How should I solve such problem? Any suggestion? Thanks

**Comment by askhade** [comment]
@JayLSU : Please create this issue in the pytorch repo. Thanks!
