### ISSUE TITLE
RuntimeError: Unable to open caffe model provided in the source model path

### ISSUE THREAD

**Issue by infinityp913** [onnx/tutorials#216]
# Ask a Question

### Question
I get the runtime error mentioned in the title when I run this tutorial: https://github.com/onnx/onnx-docker/blob/master/onnx-ecosystem/converter_scripts/caffe_coreml_onnx.ipynb
I'm running Python 2.7 because coremltools==2.1 is the supported version (as suggested in #215) which is not available on the latest Python versions.

Please let me know if you have angles on this issue.

**Comment by infinityp913** [comment]
It was a simple fix of using the right path for the models. Had a typo in the models directory in the python script

**Comment by EgorMezhin** [comment]
I had a similar problem, but it was not about spelling the model names in the script. To get rid of it, I had to move the folder with the files to the desktop, before that it was in the icloud folder.
