### ISSUE TITLE
Where can I find api documentation?

### ISSUE THREAD

**Issue by tengerye** [onnx/tutorials#229]
It took me great effort in searching for proper documentation of APIs. I would like to know what methods does the `onnxruntime.InferenceSession` have. I tried `https://onnx.ai/get-started.html` and got nothing. It seems the official website lists which tools it support but provides no API documents?

**Comment by liuziyue** [comment]
For onnxruntime related API documentation, you can refer to [ONNX Runtime API documentation](https://github.com/microsoft/onnxruntime#api-documentation). For more detail related to the `onnxruntime.InferenceSession` python class, please see https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/onnxruntime_inference_collection.py#L232 .

**Comment by tengerye** [comment]
@liuziyue Thank you for your kind reply. It would be much better that ONNX has its API documents on its official website, like PyTorch and TensorFlow.
