### ISSUE TITLE
Can you  provide a clear CMakeLists.txt example on how to make the project?

### ISSUE THREAD

**Issue by julycetc** [onnx/tutorials#230]
In the CmakeList.txt, there are many paths which need to be added, like PATH_TO_ONNXRUNTIME_TEST_UTIL_INCLUDE_DIR, PATH_TO_ONNXRUNTIME_LIB, PATH_TO_ONNXRUNTIME_INCLUDE_DIR. But  i am not sure which path they are,can you provide a clear example and explain the path clearly? Thanks very much!

cmake_minimum_required(VERSION 3.10)
project (customop)
add_definitions(-std=c++11)

set(TEST_SOURCE custom_op_test.cc)
set(HEADER custom_op.h)
set(SOURCE custom_op.h)
add_executable(customop ${SOURCE} ${HEADER} ${TEST_SOURCE})

#Include path to header files for Custom Op
include_directories(<PATH_TO_EIGEN_DIR>)
include_directories(<PATH_TO_ONNXRUNTIME_INCLUDE_DIR>)

#Include path to header files for Custom Op Test
include_directories(<PATH_TO_ONNXRUNTIME_TEST_UTIL_INCLUDE_DIR>)

#Linking dependencies for Custom Op
find_library(ONNXRUNTIME_LIBRARY onnxruntime HINTS <PATH_TO_ONNXRUNTIME_LIB>)
target_link_libraries(customop PUBLIC ${ONNXRUNTIME_LIBRARY})

**Comment by zhewenhu** [comment]
I cannot run the program either. And at line 8: set(SOURCE custom_op.h)
Shouldn't the source file be custom_op.cc?

**Comment by prasanthpul** [comment]
There is no cmakelist.txt in this repo. If this is still an issue for you, please open it in the appropriate repo that you are having the trouble with

**Comment by ahangchen** [comment]
here is the https://github.com/onnx/tutorials/blob/master/PyTorchCustomOperator/ort_custom_op/CMakeLists.txt
