### ISSUE TITLE
Could I build my own model and wrap with ONNX runtime and train under the runtime?

### ISSUE THREAD

**Issue by laurence-lin** [onnx/tutorials#240]
The documents note that ONNX provides custom trained model by AutoML service from two Azure cloud.

Now if I have my own model, built under PyTorch or Tensorflow framework, could I wrap in ONNX framework and train under the runtime?

The tutorial notebook demonstrate to execute the inference under these frameworks, and the speed up for making prediction is amazing, but I would like to know if this works for training process.

Thank you!

**Comment by pranavsharma** [comment]
onnxruntime does have limited training support. Please file an issue under onnxruntime github issues if you need any help.

**Comment by laurence-lin** [comment]
> onnxruntime does have limited training support. Please file an issue under onnxruntime github issues if you need any help.

Thank you, I will look for it.
