### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow_addons'

### ISSUE THREAD

**Issue by Ganpat9829** [onnx/tutorials#251]
from tensorflow_addons import losses
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import confusion_matrix , classification_report

**Comment by Ganpat9829** [comment]
Thank you

**Comment by chenfucn** [comment]
is tensorflow_addons module installed in your python env?

**Comment by prasanthpul** [comment]
see https://github.com/onnx/tutorials/issues/201
