### ISSUE TITLE
Why do we use ONNX to represent 'Open Neural Network Exchange' instead of ONNE?

### ISSUE THREAD

**Issue by slowlyideal** [onnx/tutorials#282]
# Ask a Question
Why do we use ONNX to represent 'Open Neural Network Exchange' instead of ONNE?

### Question
I have been working with ONNX for a while, and recently I need to introduce ONNX to others. Hence, I have this simple question: Is it because of English grammar or is there another story behind it?

### Further information
- Relevant Area (*e.g. model usage, best practices, shape_inference, version_converter, training, test*): 

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  
**Model opset** (*e.g. 7*):  
Please upload the model and provide the link if possible.

### Notes
Any additional information, code snippets.

**Comment by slowlyideal** [comment]
@jcwchen
@xadupre
anyone can help me?

**Comment by jcwchen** [comment]
Hi @slowlyideal,
Interesting question. Sorry that I don't really have the history context here (haven't worked with ONNX when ONNX was born), but I would guess "X" is closer to the prefix of "exchange" (ex). Also possibly there is some branding concern like ONNE has been well used compared to ONNX.

**Comment by jcwchen** [comment]
I will close it now. Feel free to reopen it if you still have other ONNX questions. Thanks!
