### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export operator aten::max_pool2d

### ISSUE THREAD

**Issue by dinglong1020** [onnx/tutorials#32]
env: ubuntu16 and latest verion onnx
code:  PytorchOnnxExport.py
           dummy_input = Variable(torch.randn(1, 3, 224, 224))
           model = torchvision.models.squeezenet1_1(pretrained=True)
           torch.onnx.export(model, dummy_input, "squeezenet.onnx", export_params=True)
           
Error: 
Traceback (most recent call last):
  File "PytorchOnnxExport.py", line 20, in <module>
    torch.onnx.export(model, dummy_input, "squeezenet.onnx", export_params=True)
  File "/usr/local/lib/python2.7/dist-packages/torch/onnx/__init__.py", line 12, in export
    return utils.export(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/onnx/utils.py", line 83, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names)
  File "/usr/local/lib/python2.7/dist-packages/torch/onnx/utils.py", line 150, in _export
    proto = trace.export(list(_unique_state_dict(model).values()), _onnx_opset_version)
RuntimeError: ONNX export failed: Couldn't export operator aten::max_pool2d

why?? Is there not support??

**Comment by owang** [comment]
any update? I've seen other demo code suggesting squeezenet should be exportable in onnx

**Comment by lun0522** [comment]
This has been mentioned before:
https://github.com/pytorch/pytorch/issues/2898

**Comment by KokeCacao** [comment]
`NTATION_RESIZE, config.AUGMENTATION_RESIZE), config.DIRECTORY_LOAD + ".onnx")                           [1902/1921]
  File "/home/k1412042720/RedstoneTorch/utils/load.py", line 123, in save_onnx                                     
    torch.onnx.export(cudaed_net.cpu(), dummy_input, dir, export_params=export_params, verbose=verbose)            
  File "/usr/local/lib/python2.7/dist-packages/torch/onnx/__init__.py", line 26, in export                         
    return utils.export(*args, **kwargs)                                                                           
  File "/usr/local/lib/python2.7/dist-packages/torch/onnx/utils.py", line 94, in export                            
    operator_export_type=operator_export_type)                                                                     
  File "/usr/local/lib/python2.7/dist-packages/torch/onnx/utils.py", line 234, in _export                          
    proto, export_map = graph.export([], _onnx_opset_version, False, operator_export_type)                         
RuntimeError: ONNX export failed: Couldn't export operator aten::max_pool2d_with_indices`

Same problem here, but different warning message because
`def max_pool2d(input, kernel_size, stride=None, padding=0, dilation=1,
               ceil_mode=False, return_indices=False):
    r"""Applies a 2D max pooling over an input signal composed of several input
    planes.

    See :class:`~torch.nn.MaxPool2d` for details.
    """
    ret = torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
    return ret if return_indices else ret[0]`

**Comment by offbye** [comment]
RuntimeError: ONNX export failed: Couldn't export operator aten::avg_pool2d
any update?

**Comment by lxy5513** [comment]
Me too,  ONNX export failed: Couldn't export operator aten::avg_pool2d   
Though, I set ceil_mode=False

anyone can help?

**Comment by lxy5513** [comment]
solution:  
install install pytorh==0.4.0 . 
 max_pool2d(...,  ceil_mode=False) .   
it works for me

**Comment by dashesy** [comment]
`ceil_mode=False` is different from `ceil_mode=True`, you may end up with different sizes that could not be broadcasted/concatenated in the rest of the network.

**Comment by KeremTurgutlu** [comment]
Why `ceil_mode=False` works, only difference is how to to rounding? I am bit confused here.

**Comment by dashesy** [comment]
`ceril_mode=True` will be supported soon

**Comment by soham24** [comment]
when it will be supported?

**Comment by askhade** [comment]
Closing this issue here. If this is still an issue please open it in pytorch repo instead.
