### ISSUE TITLE
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.

### ISSUE THREAD

**Issue by cl5220418** [onnx/tutorials#37]
When I run the following example in 'OnnxCaffe2Import.ipynb', the following error warning appears. I installed caffe2 in the cpu version of the anaconda environment. What should I do? Thanks!!

> import onnx
import caffe2.python.onnx.backend
\# Prepare the inputs, here we use numpy to generate some random inputs for demo purpose
import numpy as np
img = np.random.randn(1, 3, 224, 224).astype(np.float32)
\# Load the ONNX model
model = onnx.load('assets/squeezenet.onnx')
\# Run the ONNX model with Caffe2
outputs = caffe2.python.onnx.backend.run_model(model, [img])

> WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: libcurand.so.8.0: cannot open shared object file: No such file or directory
Segmentation fault (core dumped)

**Comment by Raviteja1996** [comment]
How are you able to solve the problem?
