### ISSUE TITLE
ValidationError: Input size 2 not in range [min=1, max=1] when importing with onnx-tf

### ISSUE THREAD

**Issue by benmodels** [onnx/tutorials#48]
Closed

**Comment by NoushNabi** [comment]
I also encountered the same problem. How did you solve it?

**Comment by chinhuang007** [comment]
The onnx checker is a utility tool to check whether a serialized protobuf file is acceptable according to the onnx specification. If the trained model graph cannot pass the checker, one must debug and fix the issue (onnx does not support all possible Tensorflow operators yet) before attempting the TF to onnx conversion.

**Comment by NoushNabi** [comment]
I have been able to convert my pytorch model to onnx. When I run the below code

```
import onnx
from onnx_tf.backend import prepare
model = onnx.load('output/carn.onnx')
tf_rep = prepare(model)
```
i get the below error. 
onnx.onnx_cpp2py_export.checker.ValidationError: Input size 2 not in range [min=1, max=1].
==> Context: Bad node spec: input: "161" input: "162" output: "163" op_type: "Reshape"

I appreciate if you help me to address it.

**Comment by glenn-jocher** [comment]
I have the same error. This relates closely to this issue (with code to reproduce):
https://github.com/pytorch/pytorch/issues/10446

**Comment by NoushNabi** [comment]
Thank you @glenn-jocher.
I was able to solve the issue with uninstalling and again installing the ONNX. It created pb file.
conda uninstall onnx
pip install onnx
