### ISSUE TITLE
Caffe2 Tutorials do not work

### ISSUE THREAD

**Issue by anirudhacharya** [onnx/tutorials#49]
In this link - https://github.com/onnx/tutorials/blob/master/tutorials/Caffe2OnnxExport.ipynb when I try to run ``python -m caffe2.python.models.download squeezenet`` I encounter a HTTP 404
```bash
$ python -m caffe2.python.models.download squeezenet
Downloading from https://s3.amazonaws.com/caffe2/models/squeezenet/predict_net.pb
Abort: Could not download model. [HTTP Error] 404: Not Found.
Cleaning up...
```

**Comment by jjiang2cal** [comment]
I ran the command today and it was ok
