### ISSUE TITLE
the coreml tutorial can't run with squeezenet.oonx

### ISSUE THREAD

**Issue by oneTaken** [onnx/tutorials#5]
In the OnnxCoremlImport.ipynb,
when changing the model name into `assets/squeezenet.onnx`, the convert code will raise 
`IndexError: list index (2) out of range`.
If `print(onnx.helper.printable_graph(model.graph))`shows the conv layer padding size is 4, however, the pooling padding size is 2.
And in the onnx_coreml code,  it would check all padding must be 4.
So, this is the problem.
How to solve this?

**Comment by houseroad** [comment]
We updated the squeezenet.onnx already. Let me know if you still have the issue.
