### ISSUE TITLE
So confused about the tutorial in onnx to cntk model

### ISSUE THREAD

**Issue by OwenLiuzZ** [onnx/tutorials#53]
It's so confused about the tutorial that show how to transfer a onnx file to a real model.
Can somebody give some hints about that?

**Comment by ebarsoum** [comment]
Hi @OwenLiuzZ 

Can you be more specific? Are you confused on saving CNTK model to ONNX or loading ONNX model to CNTK?

**Comment by OwenLiuzZ** [comment]
Hi @ebarsoum ,
For the tutorial in CNTK, I found there maybe a minor mistake about inporting onnx in step 2:
`import cntk as C
z = C.Function.load("vgg19/model.pb", device=C.device.cpu(), format=C.ModelFormat.ONNX)`

instead, I replace .pb file to .onnx file than it works.

**Comment by OwenLiuzZ** [comment]
Another question is that can we change other onnx file to get the same prediction?
For example, I use my own vgg wrote by the tensorflow and then transfer it to .onnx file.
Then, the following steps are all the same like the tutorial.
Can it work?

**Comment by ebarsoum** [comment]
Yes, once you saved the model as ONNX. You can load it in CNTK (or other framework that support ONNX) similar to the above.

**Comment by OwenLiuzZ** [comment]
However, it does not work for me. For example, using the tutorial code in CNTK, both pre-trained models are from the official repository(Microsoft). When I replaced the model from ResNet20_CIFAR10_CNTK.model to ResNet110_CIFAR10_CNTK.model and  the error will be shown like that:
`Traceback (most recent call last):`
  `File "test_restnet20.py", line 6, in <module>`
   ` z.save("resnet110_cifar10_model.onnx", format=C.ModelFormat.ONNX)`
  `File "/root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/internal/swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)`
 ` File "/root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/ops/functions.py", line 1532, in save`
   ` return super(Function, self).save(filename, format.value)`
 ` File "/root/anaconda3/envs/cntk-py35/lib/python3.5/site-packages/cntk/cntk_py.py", line 2064, in save`
   ` return _cntk_py.Function_save(self, *args)`
`RuntimeError: Node 'TransposeTimes: Placeholder('Placeholder3275', [#], [10]), Placeholder('Placeholder3276', [#], [10]) -> Output('TransposeTimes124989_Output_0', [#], [1])': Unsupported node.`

**Comment by ebarsoum** [comment]
Not all CNTK nodes have ONNX equivalent, we are working on adding the support for the remaining ones.

**Comment by spandantiwari** [comment]
@OwenLiuzZ - Did I understand you right that you are not able to export (save) pre-trained Resnet110 CNTK model from official CNTK repository? Or is it the Tensorflow resnet that is throwing an error? If it is the latter, can you share the model?

**Comment by OwenLiuzZ** [comment]
@spandantiwari  Yes, your understanding is correct!  I downloaded from official CNTK repository , please see the link below:
[official CNTK repository](https://github.com/Microsoft/CNTK/blob/master/PretrainedModels/Image.md)

**Comment by OwenLiuzZ** [comment]
@ebarsoum OK, that's say the tutorial is just work for one model(which is ResNet20 for CIFAR-10)?
Did I understand correctly ?

**Comment by spandantiwari** [comment]
OK, thanks for clarifying. Resnet20 seems to be exporting fine. But Resnet110 has a node which we do not support for export. We are in the process of adding support for that.

**Comment by OwenLiuzZ** [comment]
@spandantiwari @ebarsoum  Thanks a lot for both of you. The work is very useful !
