### ISSUE TITLE
error with tf-onnx when export in the last step Inference using Backend

### ISSUE THREAD

**Issue by OwenLiuzZ** [onnx/tutorials#55]
After I convert the model to ONNX format using onnx-tensorflow and I can get the correct output format:
`input: "Placeholder"`
`input: "reshape/Reshape/shape"`
`output: "reshape/Reshape"`
`op_type: "Reshape"`
However when I run in the last step: **Inference using Backend**
I get the error information:
`tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 16 and 64 for 'Add_1' (op: 'Add') with input shapes: [?,64,?,16], [1,1,1,64].`
 and the details as follow:
`Traceback (most recent call last):`
  `File "test_mnist_using_onnx.py", line 6, in <module>`
    `tf_rep = prepare(model)`
 ` File "/root/anaconda3/lib/python3.6/site-packages/onnx_tf/backend.py", line 348, in prepare
    model.graph, opset=model.opset_import[0].version))`
  `File "/root/anaconda3/lib/python3.6/site-packages/onnx_tf/backend.py", line 324, in onnx_graph_to_tensorflow_net
    node, tensor_dict, opset=opset)`
  `File "/root/anaconda3/lib/python3.6/site-packages/onnx_tf/backend.py", line 407, in _onnx_node_to_tensorflow_op
    return method_to_call(node, input_dict)`
 ` File "/root/anaconda3/lib/python3.6/site-packages/onnx_tf/backends/backend_v6.py", line 27, in handle_add
    return TensorflowBackendV1.handle_add(node, input_dict)`
  `File "/root/anaconda3/lib/python3.6/site-packages/onnx_tf/backends/backend_v1.py", line 40, in handle_add
    return [cls._bin_op(node, input_dict, tf.add)]`
 ` File "/root/anaconda3/lib/python3.6/site-packages/onnx_tf/backend.py", line 239, in _bin_op
    return op_func(x, y)`
  `File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 297, in add
    "Add", x=x, y=y, name=name)`
  `File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)`
 ` File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)`
  `File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)`
  `File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))`
`ValueError: Dimensions must be equal, but are 16 and 64 for 'Add_1' (op: 'Add') with input shapes: [?,64,?,16], [1,1,1,64].`

**Comment by knandanan** [comment]
@OwenLiuzZ Did you find a solution to this issue? Please let me know

**Comment by OwenLiuzZ** [comment]
@knandanan  Sorry, not yet. I suppose that there may exist a bug to analyze the ONNX file in API.

**Comment by knandanan** [comment]
@OwenLiuzZ oh okay

**Comment by houseroad** [comment]
wanna create one issue in the corresponding repo onnx/onnx-tf or onnx/tf-onnx?

**Comment by amsalien** [comment]
Did anyone find a solution to this issue?

**Comment by dbodily1** [comment]
Still no?
