### ISSUE TITLE
Black screen on iPhone 5s on iOS 11.4.1

### ISSUE THREAD

**Issue by rahulbhalley** [onnx/tutorials#58]
I followed the tutorial but the screen turns black and shows no style transfer via camera. I'm using iOS 11.4.1 on iPhone 5s.
Please help and thanks in advance!

**Comment by AnkitPurohit01** [comment]
HI,
Did you face any error when running the script **onnx_to_coreml.py** to convert the model from onnx to coreml like _"segmentation fault : 11"_??

If yes, how did you solve it?

**Comment by glenn-jocher** [comment]
@rahulbhalley I had the same problem, reported it in issue #89. Did you solve it?

**Comment by soumith** [comment]
@rahulbhalley looks like @glenn-jocher found the issue and workaround here: https://github.com/onnx/tutorials/issues/89#issuecomment-444510284, does this help for you as well?

**Comment by rahulbhalley** [comment]
@soumith I'm now stuck with **segmentation fault: 11**. I deleted all the git clones given in tutorial and re-iterated over the tutorial instructions but still I'm stuck with **segmentation fault: 11**.

**Comment by rahulbhalley** [comment]
It's been 2 years and there's no response. So closing this issue.
