### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export operator aten::adaptive_avg_pool2d

### ISSUE THREAD

**Issue by MBocchi** [onnx/tutorials#63]
Hi I've tried to export PyTorch model to ONNX as following:
`input_shape = (3, 224, 224)`
`model_onnx_path = "torch_model.onnx"`
`dummy_input = Variable(torch.randn(1, *input_shape).cuda())`
`output = torch.onnx.export(model, dummy_input, model_onnx_path, verbose=False)`

And I got this error:
`UserWarning: ONNX export failed on ATen operator adaptive_avg_pool2d because torch.onnx.symbolic.adaptive_avg_pool2d does not exist`
`RuntimeError: ONNX export failed: Couldn't export operator aten::adaptive_avg_pool2d`

How I can fixed it? Thank you

**Comment by houseroad** [comment]
https://github.com/onnx/tutorials/blob/master/tutorials/PytorchAddExportSupport.md

Almost up to date tutorial, try to follow it.

**Comment by cnaaq** [comment]
@MBocchi Did you resolve the problem?
I face the same problem and honestly, I didn't get that much from PytorchAddExportSupport.md.

**Comment by jjkislele** [comment]
@cnaaq @MBocchi Sorry for bothering you, perhaps I have found a solution. 

Please see https://github.com/pytorch/pytorch/issues/14395#issuecomment-444697403

When you transform a Pytorch model to ONNX, using ``torch.onnx.export``, you might add option ``operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK`` to allow you to use ops in Aten when cannot find it in ONNX operator set. It works for me, when I use ``torch.nn.AdaptiveAvgPool2d`` in a PyTorch network.

**Comment by fontno** [comment]
> @cnaaq @MBocchi Sorry for bothering you, perhaps I have found a solution.
> 
> Please see [pytorch/pytorch#14395 (comment)](https://github.com/pytorch/pytorch/issues/14395#issuecomment-444697403)
> 
> When you transform a Pytorch model to ONNX, using `torch.onnx.export`, you might add option `operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK` to allow you to use ops in Aten when cannot find it in ONNX operator set. It works for me, when I use `torch.nn.AdaptiveAvgPool2d` in a PyTorch network.

Appreciate this @jjkislele. Solved my problem.

**Comment by PatrickNa** [comment]
I faced the same issue as described above and successfully exported the model with the flag `operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK`. However it reappears when the model is loaded with onnxruntime afterwards:

`Fail: [ONNXRuntimeError] : 1 : FAIL : Fatal error: ATen is not a registered function/op`

I therefore do not consider this as a solution. Does anyone have an idea on what else could be tried out?

**Comment by PatrickNa** [comment]
I noticed that I was running the export with an older pytorch version so I updated and receive the following error now:

`RuntimeError: Exporting the operator max_unpool2d to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.`

I also tried it with opset version 12.

**Comment by jjkislele** [comment]
@PatrickNa 
I'd like to say, yes, actually it is a bad way, as the same behaviour as the ostrich puts its head in a hole. Maybe you should raise an issue to pursue the developer for supporting the op you need. Maybe you should hack the source code inside and modify them to support the op you need. 

In fact, I face this problem when I want to convert my PyTorch model to TensorRT/OpenVINO model via ONNX. I have tried another PyTorch pool operation: nn.AvgPooling instead of nn.AdaptiveAvgPool2d. So perhaps, you might replace the max pool function based on PyTorch.

Hope it would help you. :-D

**Comment by rGitcy** [comment]
I use the code to convert Adaptivateavgpool2d --> Avgpool2, and i export onnx successful!
My code list:
______________________________
import torch
import torch.nn as nn
import numpy as np

m = nn.AdaptiveAvgPool2d((None,1))
input = torch.randn(64, 26, 512, 1) #my inputs shape
output = m(input)
print(output.shape)

# add code for adaptiveavgpool2d -> avgpoll2d #
alist = torch.randn(64, 26, 512, 1)
inputsz = alist
outputsz = alist

stridesz = np.floor((inputsz / outputsz))
print("stride size", stridesz.shape)

kernelsz = inputsz - (outputsz - 1) * stridesz
print("kernal size", kernelsz.shape)
##test##
adp = nn.AdaptiveAvgPool2d(list(outputsz))
avg = nn.AvgPool2d(kernel_size=list(kernelsz), stride=list(stridesz))
adplist = adp(alist)
avglist = avg(alist)

print(alist)
print(adplist)
print(avglist)

______________________________

**Comment by garymm** [comment]
Some support for this op was added in https://github.com/pytorch/pytorch/pull/17412.
Support for remaining cases is tracked by https://github.com/pytorch/pytorch/issues/42653.

@jcwchen can you please close this issue?

**Comment by nvhungv2k** [comment]
> @cnaaq @MBocchi Sorry for bothering you, perhaps I have found a solution.
> 
> Please see [pytorch/pytorch#14395 (comment)](https://github.com/pytorch/pytorch/issues/14395#issuecomment-444697403)
> 
> When you transform a Pytorch model to ONNX, using `torch.onnx.export`, you might add option `operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK` to allow you to use ops in Aten when cannot find it in ONNX operator set. It works for me, when I use `torch.nn.AdaptiveAvgPool2d` in a PyTorch network.

Your suggest is very useful for me. Thanks a lot!
