### ISSUE TITLE
Saving a PyTorch model

### ISSUE THREAD

**Issue by ShreyasSkandan** [onnx/tutorials#82]
I have a custom model that's not very complicated 
It's just a combination of Conv2D, MaxPool2D, BatchNorm2D and Dropout2D and one ConvTranspose2D.

I'm trying to save this model to file using the torch.onnx.export() function, but I get this error:

*** RuntimeError: tuple appears in op that does not forward tuples (VisitNode at ../torch/csrc/jit/passes/lower_tuples.cpp:72)

Any ideas are appreciated.

Thanks,
S

**Comment by houseroad** [comment]
I think you input format may not be correct. Could you provide more details?

**Comment by ShreyasSkandan** [comment]
Hi @houseroad I fixed this by following the recommendations in this issue: https://github.com/pytorch/pytorch/issues/13397
