### ISSUE TITLE
pytorch shufflenet export to onnx failed

### ISSUE THREAD

**Issue by cswwp** [onnx/tutorials#83]
It shows: "RuntimeError: ONNX export failed: Couldn't export operator aten::max_pool2d_with_indices"
but i scan the '/torch/onnx/symbolic.py' file, and it already has the max_pool2d_with_indices function
`@parse_args('v', 'is', 'is', 'is', 'is', 'i')
def max_pool2d_with_indices(g, input, kernel_size, stride, padding, dilation, ceil_mode):
    if ceil_mode:
        return _unimplemented("max_pool2d_with_indices", "ceil_mode")
    if set(_pair(dilation)) != {1}:
        return _unimplemented("max_pool2d_with_indices", "dilation")
    if not stride:
        stride = kernel_size
    r = g.op("MaxPool", input,
             kernel_shape_i=_pair(kernel_size),
             pads_i=_pair(padding) * 2,
             strides_i=_pair(stride))
    return r, None`
anyone help?

/home/parker/work/book_pytorch_demo/shufflenet_v2.py:57: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  x1 = x[:, :(x.shape[1]//2), :, :]
/home/parker/work/book_pytorch_demo/shufflenet_v2.py:58: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  x2 = x[:, (x.shape[1]//2):, :, :]
/home/parker/anaconda2/envs/demo/lib/python3.6/site-packages/torch/onnx/symbolic.py:130: UserWarning: ONNX export failed on max_pool2d_with_indices because ceil_mode not supported
  warnings.warn("ONNX export failed on " + op + " because " + msg + " not supported")
/home/parker/anaconda2/envs/demo/lib/python3.6/site-packages/torch/onnx/utils.py:500: UserWarning: ONNX export failed on ATen operator reshape because torch.onnx.symbolic.reshape does not exist
  .format(op_name, op_name))
Traceback (most recent call last):
  File "shufflenet.py", line 24, in <module>
    export_params=True)      # store the trained parameter weights inside the model file
  File "/home/parker/anaconda2/envs/demo/lib/python3.6/site-packages/torch/onnx/__init__.py", line 22, in _export
    return utils._export(*args, **kwargs)
  File "/home/parker/anaconda2/envs/demo/lib/python3.6/site-packages/torch/onnx/utils.py", line 286, in _export
    proto, export_map = graph.export(params, _onnx_opset_version, defer_weight_export, operator_export_type)
RuntimeError: ONNX export failed: Couldn't export operator aten::max_pool2d_with_indices

**Comment by 3160104812** [comment]
> It shows: "RuntimeError: ONNX export failed: Couldn't export operator aten::max_pool2d_with_indices"
> but i scan the '/torch/onnx/symbolic.py' file, and it already has the max_pool2d_with_indices function
> `@parse_args('v', 'is', 'is', 'is', 'is', 'i') def max_pool2d_with_indices(g, input, kernel_size, stride, padding, dilation, ceil_mode): if ceil_mode: return _unimplemented("max_pool2d_with_indices", "ceil_mode") if set(_pair(dilation)) != {1}: return _unimplemented("max_pool2d_with_indices", "dilation") if not stride: stride = kernel_size r = g.op("MaxPool", input, kernel_shape_i=_pair(kernel_size), pads_i=_pair(padding) * 2, strides_i=_pair(stride)) return r, None`
> anyone help?
> 
> /home/parker/work/book_pytorch_demo/shufflenet_v2.py:57: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
> x1 = x[:, :(x.shape[1]//2), :, :]
> /home/parker/work/book_pytorch_demo/shufflenet_v2.py:58: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
> x2 = x[:, (x.shape[1]//2):, :, :]
> /home/parker/anaconda2/envs/demo/lib/python3.6/site-packages/torch/onnx/symbolic.py:130: UserWarning: ONNX export failed on max_pool2d_with_indices because ceil_mode not supported
> warnings.warn("ONNX export failed on " + op + " because " + msg + " not supported")
> /home/parker/anaconda2/envs/demo/lib/python3.6/site-packages/torch/onnx/utils.py:500: UserWarning: ONNX export failed on ATen operator reshape because torch.onnx.symbolic.reshape does not exist
> .format(op_name, op_name))
> Traceback (most recent call last):
> File "shufflenet.py", line 24, in
> export_params=True) # store the trained parameter weights inside the model file
> File "/home/parker/anaconda2/envs/demo/lib/python3.6/site-packages/torch/onnx/**init**.py", line 22, in _export
> return utils._export(*args, **kwargs)
> File "/home/parker/anaconda2/envs/demo/lib/python3.6/site-packages/torch/onnx/utils.py", line 286, in _export
> proto, export_map = graph.export(params, _onnx_opset_version, defer_weight_export, operator_export_type)
> RuntimeError: ONNX export failed: Couldn't export operator aten::max_pool2d_with_indices

set 'ceil_mode' in max_pool....() as False

**Comment by drogen120** [comment]
> ceil_mode

Yes, it fixed the problem.
Thank you!

**Comment by houseroad** [comment]
Close since it's fixed.

**Comment by Casablancaaa** [comment]
@cswwp  have you fixed the warning??
