### ISSUE TITLE
Tutorial on Importing ONNX model in TensorRT (nvidia runtime)

### ISSUE THREAD

**Issue by YogeshShitole** [onnx/tutorials#9]
ONNX list nvidia runtime in supported tools section but I cant find any documentation on deployment of ONNX model in TensorRT...please can we have tutorial on this topic
suggestions and help really appreciated
thanks in advance

**Comment by hengck23** [comment]
There could be an example in the tensorrt container?

http://docs.nvidia.com/deeplearning/dgx/tensorrt-release-notes/rel_17.12.html
http://docs.nvidia.com/deeplearning/dgx/tensorrt-release-notes/running.html#cli-options

"The example Inception-v1 ONNX model and the onnx_inception_v1 script are also located in the /workspace/tensorrt_server directory. This example and script runs the REST server to provide inference for that model via an HTTP endpoint."

**Comment by sidgoyal78** [comment]
There doesn't seem to be any example source code in the container. It has a binary `onnx_inception_v1` and the model protobuf (`inception_v1.pb`).

**Comment by BobLiu20** [comment]
review here:
https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#onnx_workflow

**Comment by BrainPotter** [comment]
@YogeshShitole could you share me your AOD-Net training programs,my email address is junnian_L@163.com. Thank you very much! I am very interested in AOD-Net now.
