### ISSUE TITLE
Failed to run after importing network (onnx-tf)

### ISSUE THREAD

**Issue by Terizian** [onnx/tutorials#90]
I've been trying to move a network from Matlab to Python via ONNX framwork. Here are the steps I've followed:

1. After training the model on Matlab, I've exported it to an ONNX Network via the "exportONNXNetwork" function. This model is a classifier for images and takes in a (224, 224, 3) image as an input. After export, I view the network on Netron and it seems that the data or input layer is expecting a 1x3x224x224 input.

2. On my Python environment, I have tried to import via three of the available frameworks: CNTK, Apache MXNet and TensorFlow. With the former two, the code throws an error at the model loading stage. With Tensorflow, I manage to load the model. 

3. Using the prepare command in onnx_tf.backend, I get the TensorflowRep object of the model. Printing it's characteristics, here's what the data layer is expecting: 
`'data_AvgImg': <tf.Tensor 'Const:0' shape=(1, 3, 224, 224) dtype=float32>`

4. To test the network, I have converted an image to a Tensor of the same data type and shape. When running the network on this input, I get the following error:
`TypeError: The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles.For reference, the tensor object was Tensor("data:0", shape=(1, 3, 224, 224), dtype=float32) which was passed to the feed with key Tensor("data:0", shape=(1, 3, 224, 224), dtype=float32).`

Note that when I import the model after export on Matlab, the network works just find.

**Comment by prasanthpul** [comment]
Have you tried using [ONNX Runtime](https://github.com/microsoft/onnxruntime)?

**Comment by Terizian** [comment]
> Have you tried using [ONNX Runtime](https://github.com/microsoft/onnxruntime)?
I have opened the network using Netron and it seems that it has the following ONNX Operator Set Version: ai.onnx v6

Does this affect anything?

**Comment by prasanthpul** [comment]
ONNX Runtime supports opset 7 and higher. Sounds like MATLAB is producing opset 6. You can try using the [version converter](https://github.com/onnx/onnx/blob/master/docs/VersionConverter.md) to upgrade your model and see if that helps.

**Comment by Terizian** [comment]
> ONNX Runtime supports opset 7 and higher. Sounds like MATLAB is producing opset 6. You can try using the [version converter](https://github.com/onnx/onnx/blob/master/docs/VersionConverter.md) to upgrade your model and see if that helps.

I tried to use the Version Converter to bump it up to version 7 but I get a RuntimeError:
`RuntimeError: Inferred shape and existing shape differ in rank: (2) vs (4)`

**Comment by prasanthpul** [comment]
@linkerzhang suggestions?

**Comment by prasanthpul** [comment]
@Terizian are you able to share the model?

**Comment by prasanthpul** [comment]
@Terizian Are you able to host it on OneDrive or similar service and share a link?

**Comment by Terizian** [comment]
> @Terizian Are you able to host it on OneDrive or similar service and share a link?

Hi there,
Thanks for all your help but onnx-tf worked out in the end!
