### ISSUE TITLE
ONNX export failed: Couldn't export operator aten::upsample_bilinear2d

### ISSUE THREAD

**Issue by chunniunai220ml** [onnx/tutorials#93]
Hi, I have follow the 
https://github.com/onnx/tutorials/blob/master/tutorials/PytorchTensorflowMnist.ipynb
to transform a pytorch model to tensorflow by onnx,  error as follows:

![image](https://user-images.githubusercontent.com/17668109/50131271-669a3480-02bc-11e9-9dd2-faae84ceadee.png)

as the custom network has the code:
x=torch.nn.upsample(x,(x.sixe(2)*2,x.sixe(3)*2),mode='bilinear',align_corners=True) in forward func, specifically net work in https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/models/hacnn.py

**Comment by ThisIsIsaac** [comment]
What was the cause of the error? I am getting a very similar error
```
RuntimeError: ONNX export failed: Couldn't export operator aten::logdet
```

**Comment by lxy5513** [comment]
I am also getting similar error,   
`ONNX export failed: Couldn't export operator aten::upsample_bilinear2d` 

@prasanthpul  @chunniunai220ml have you solved this problem?

**Comment by ZhongXiaoFang** [comment]
I  got the same error. the function named "upsample_bilinear2d" is complete at the symbolic.py file.

**Comment by ckf1111** [comment]
You can try that  torch.onnx.export(..,opset_version=11)

**Comment by thierrypin** [comment]
I'm also having the same problem. Have anyone found a solution? @lxy5513 @ZhongXiaoFang 
Exporting to opset 11 solves the issue, but this opset is not an option for me.

I get the same error you do, plus:
`UserWarning: ONNX export failed on upsample_bilinear2d because torch._C.Value (output_size) indexing not supported`
